# Generated by Django 5.1.2 on 2024-10-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_remove_rate_purity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='rate',
        ),
    ]
